name: Build distributable artifacts

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheel
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'

      - name: build and test wheel
        run: make wheel

      - name: upload wheel
        uses: actions/upload-artifact@v3
        with:
          path: ./dist/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Build and test sdist
        run: make sdist

      - name: upload sdist
        uses: actions/upload-artifact@v3
        with:
          path: ./dist/*.tar.gz
